# Generated by Django 3.1.1 on 2020-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_agree_location',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_agree_sms',
            field=models.DateTimeField(null=True),
        ),
    ]
