# Generated by Django 3.1.1 on 2020-11-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchCount',
        ),
    ]
