# Generated by Django 3.1.1 on 2020-11-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20201114_1353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='center',
            table=None,
        ),
    ]
