# Generated by Django 3.1.1 on 2020-11-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20201125_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='n_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
