# Generated by Django 3.1.1 on 2020-11-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_n_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='n_id',
            field=models.IntegerField(null=True),
        ),
    ]
