# Generated by Django 3.1.1 on 2020-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_auto_20201125_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='n_id',
            field=models.IntegerField(default=0),
        ),
    ]
