# Generated by Django 3.1.1 on 2020-11-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_auto_20201125_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='n_id',
            field=models.IntegerField(null=True),
        ),
    ]
